FROM ghcr.io/foundry-rs/foundry:v1.3.2

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       curl ca-certificates jq \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL get.huff.sh | bash \
    && /root/.huff/bin/huffup \
    && /root/.huff/bin/huffc --version

ENV PATH="/root/.huff/bin:${PATH}"

WORKDIR /baanx/demo
CMD ["/baanx/demo/scripts/deploy_all.sh"]

