#!/bin/bash

echo "🎭 Starting Self Protocol with Mock Backend"
echo "=========================================="
echo ""

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
    echo "❌ ngrok is not installed"
    echo ""
    echo "Install ngrok:"
    echo "  Mac: brew install ngrok"
    echo "  Other: https://ngrok.com/download"
    echo ""
    exit 1
fi

echo "✅ ngrok is installed"
echo ""

# Start mock backend if not running
if ! lsof -Pi :3001 -sTCP:LISTEN -t >/dev/null ; then
    echo "Starting mock backend..."
    cd backend
    node mock-server.js > /tmp/mock-backend.log 2>&1 &
    BACKEND_PID=$!
    cd ..
    sleep 2
    echo "✅ Mock backend started (PID: $BACKEND_PID)"
else
    echo "✅ Mock backend already running"
fi

# Check if ngrok is already running on port 4040
if lsof -Pi :4040 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ ngrok is already running"
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o 'https://[^"]*ngrok[^"]*' | head -1)
else
    echo "Starting ngrok tunnel for backend (port 3001)..."
    ngrok http 3001 --log=stdout > /tmp/ngrok-backend.log 2>&1 &
    NGROK_PID=$!
    
    # Wait for ngrok to start
    sleep 3
    
    # Get ngrok URL
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o 'https://[^"]*ngrok[^"]*' | head -1)
    
    if [ -z "$NGROK_URL" ]; then
        echo "❌ Failed to get ngrok URL"
        cat /tmp/ngrok-backend.log
        exit 1
    fi
    
    echo "✅ ngrok started (PID: $NGROK_PID)"
fi

echo ""
echo "✅ Your public backend URL: $NGROK_URL"
echo ""

# Create .env.demo for UI
cd ui
cat > .env.demo << EOF
# Self Protocol Mock Backend URL
# Generated by start-self-mock.sh
VITE_SELF_CALLBACK_URL=${NGROK_URL}/api/self-callback
EOF

echo "✅ Created ui/.env.demo with callback URL"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. In a NEW terminal, start the UI:"
echo "   cd /Users/0xblockbird/Cursor/Bermuda/baanx/demo/ui"
echo "   npm run start"
echo ""
echo "2. Open your browser to:"
echo "   http://localhost:4193"
echo ""
echo "3. Test Self Protocol verification!"
echo ""
echo "⚠️  IMPORTANT: Keep this terminal open!"
echo "   (ngrok and mock backend must stay running)"
echo ""
echo "📊 Monitor:"
echo "   Mock Backend logs: tail -f /tmp/mock-backend.log"
echo "   ngrok logs: tail -f /tmp/ngrok-backend.log"
echo ""

