import type { NextApiRequest, NextApiResponse } from "next";
import { ethers } from "ethers";
import { createSafeLogger } from "../../../lib/sanitize";

const logger = createSafeLogger("NillionAttest");

/**
 * Demo Nillion Attestation Endpoint
 * 
 * This is a MOCK attestation service. In production, this would:
 * 1. Connect to Nillion nilCC network
 * 2. Verify the policy in a Confidential VM (TEE)
 * 3. Generate attestation from the TEE attestation report
 * 4. Return cryptographic proof that policy allows the action
 * 
 * For now, we use a simple ECDSA signature from a demo keypair.
 */

const ATTESTOR_PK = process.env.NILLION_DEMO_ATTESTOR_PK; // demo private key
const DEMO_ATTESTOR_WALLET = ATTESTOR_PK ? new ethers.Wallet(ATTESTOR_PK) : null;

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Only allow POST requests
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  if (!DEMO_ATTESTOR_WALLET) {
    logger.error("NILLION_DEMO_ATTESTOR_PK not set in environment");
    return res.status(500).json({ 
      error: "Attestor private key not configured",
      hint: "Set NILLION_DEMO_ATTESTOR_PK in .env.local",
      note: "This is a demo/mock attestation. Production will use Nillion nilCC."
    });
  }

  try {
    const { leafCommitment, actionHash, latestRoot } = req.body || {};
    
    // Validate inputs
    if (!leafCommitment || !actionHash || !latestRoot) {
      return res.status(400).json({ 
        error: "Missing required fields",
        required: ["leafCommitment", "actionHash", "latestRoot"],
        received: {
          leafCommitment: !!leafCommitment,
          actionHash: !!actionHash,
          latestRoot: !!latestRoot
        }
      });
    }

    logger.log("Nillion attestation request", { hasLeaf: !!leafCommitment, hasAction: !!actionHash, hasRoot: !!latestRoot });

    // Demo: Sign keccak256(leafCommitment || actionHash || latestRoot)
    // In production, this would be generated by Nillion nilCC TEE
    const digest = ethers.keccak256(
      ethers.AbiCoder.defaultAbiCoder().encode(
        ["bytes32", "bytes32", "bytes32"],
        [leafCommitment, actionHash, latestRoot]
      )
    );
    
    // Sign with demo attestor wallet
    const sig = await DEMO_ATTESTOR_WALLET.signMessage(ethers.getBytes(digest));
    
    logger.log("Nillion attestation generated (demo)", { attestor: DEMO_ATTESTOR_WALLET.address });
    
    return res.status(200).json({ 
      attestation: sig,
      attestor: DEMO_ATTESTOR_WALLET.address,
      digest: digest,
      note: "This is a demo/mock attestation. Production will use Nillion nilCC."
    });
  } catch (e: any) {
    logger.error("Nillion attestation failed", { error: e?.message || 'Unknown error' });
    return res.status(500).json({ 
      error: e?.message || "attest failed",
      details: e?.reason || "Unknown error"
    });
  }
}

