#!/bin/bash

echo "🚀 Self Protocol Setup for Baanx PPOI"
echo "======================================"
echo ""
echo "Self Protocol requires a PUBLIC URL (not localhost)."
echo "We'll set up ngrok to create one."
echo ""

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
    echo "❌ ngrok is not installed"
    echo ""
    echo "Install ngrok:"
    echo "  Mac: brew install ngrok"
    echo "  Other: https://ngrok.com/download"
    echo ""
    exit 1
fi

echo "✅ ngrok is installed"
echo ""

# Check if ngrok is already running
if lsof -Pi :4040 -sTCP:LISTEN -t >/dev/null ; then
    echo "✅ ngrok is already running"
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o 'https://[^"]*ngrok[^"]*' | head -1)
else
    echo "Starting ngrok..."
    echo "⚠️  Keep this terminal window open!"
    echo ""
    ngrok http 4193 --log=stdout > /tmp/ngrok.log 2>&1 &
    NGROK_PID=$!
    
    # Wait for ngrok to start
    sleep 3
    
    # Get ngrok URL
    NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o 'https://[^"]*ngrok[^"]*' | head -1)
    
    if [ -z "$NGROK_URL" ]; then
        echo "❌ Failed to get ngrok URL. Check if ngrok started correctly."
        cat /tmp/ngrok.log
        exit 1
    fi
fi

echo ""
echo "✅ Your public URL: $NGROK_URL"
echo ""

# Create .env.demo
cat > .env.demo << EOF
# Self Protocol Callback URL
# Generated by setup-self-protocol.sh
# Note: Vite requires VITE_ prefix for env vars
VITE_SELF_CALLBACK_URL=${NGROK_URL}/api/self-callback
EOF

echo "✅ Created .env.demo with callback URL"
echo ""
echo "📋 Next Steps:"
echo ""
echo "1. Start your dev server in ANOTHER terminal:"
echo "   cd /Users/0xblockbird/Cursor/Bermuda/baanx/demo/ui"
echo "   npm run start"
echo ""
echo "2. Open your browser to the ngrok URL (NOT localhost):"
echo "   $NGROK_URL"
echo ""
echo "3. Test Self Protocol verification!"
echo ""
echo "⚠️  IMPORTANT: Keep this terminal open while testing!"
echo "   (ngrok must stay running)"
echo ""

